# Generated by Django 5.1.5 on 2025-02-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breeddb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Breed_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Alpha_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
                ('Health', models.CharField(blank=True, max_length=100, null=True)),
                ('Training', models.CharField(blank=True, max_length=100, null=True)),
                ('Exercise', models.CharField(blank=True, max_length=100, null=True)),
                ('breed_image', models.ImageField(blank=True, null=True, upload_to='Breed images')),
            ],
        ),
    ]
