# Generated by Django 5.1.5 on 2025-02-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breeddb',
            name='Description',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='breeddb',
            name='Exercise',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='breeddb',
            name='Health',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='breeddb',
            name='Training',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
